config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "main#index"
  get "/signup", to: "signup#new"
  post "/signup", to: "signup#create"

  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  delete "/signout", to: "sessions#destroy"

  resources :toys
  get "/dashboard", to: "toys#dashboard"

  get "/about", to: "about#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/toy.rb
class Toy < ApplicationRecord
  belongs_to :user
  has_many_attached :images

  validates :toy_name, presence: true
  validates :description, length: { maximum: 400 }
  validates :images, content_type: { in: %w[image/jpeg image/gif image/png], message: "must be a jpeg, gif, or png file" },
                    size: { less_than: 5.megabytes, message: "Should be less than 5MB" }
end

app/models/user.rb
# email: string
# password_digest: string
# password: string virtual
# password_confirmation: string virtual

class User < ApplicationRecord
    has_many :toys
    
    has_secure_password
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    before_save { email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX, message: "Must be a valid email address" }, 
                                      length: { maximum: 255 }, uniqueness: true
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    
    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    def require_user_logged_in! # what does this exclamation point do?
        redirect_to signin_path, alert: "You must be signed in to do that." if Current.user.nil?
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
        if Current.user 
            redirect_to toys_path
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id 
            redirect_to toys_path, notice: "Logged in successfully"
        else
            redirect_to signin_path, alert: "Invalid email or password"
        end
    end
    
    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out"
    end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(params_user)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Successfully created account"
        else
            render :new, status: :unprocessable_entity
        end
    end

    private

    def params_user
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
    before_action :require_user_logged_in!
    before_action :set_toy, only: [:edit, :update, :destroy]

    def index
        @toys = Toy.all
    end

    def dashboard
        @toys = Current.user.toys
    end

    def new
        @toy = Toy.new
    end

    def create
        @toy = Current.user.toys.new(params_toy)
        @toy.images.attach(params[:images])
        if @toy.save
            redirect_to toys_path, notice: "Toy has been listed"
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
    end

    def update
        if @toy.update(params_toy)
            redirect_to toys_path, notice: "Toy has been updated successfully"
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @toy.destroy
        redirect_to toys_path, notice: "Toy was removed from your list"
    end

    private

    def params_toy
        params.require(:toy).permit(:toy_name, :category, :description, images: [])
    end

    def set_toy
        @toy = Current.user.toys.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About the Toy App</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
    <h1>Welcome to the Toy App</h1>
    <div>
    </div>
</div>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert">
        <%= flash.now[:notice] %>
    </div>
<% end %>
<% if flash[:alert] %>
    <div class="alert alert-warning mt-4" role="alert">
        <%= flash.now[:alert] %>
    </div>
<% end %>

app/views/shared/_form_error.html.erb
<% if form.object.errors.any? %>
    <div class="col-6 alert alert-danger offset-3 pe-0">
        <% form.object.errors.full_messages.each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark sticky-top bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Toy App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <% if Current.user %>
          <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
        <% end %>
        <%= link_to "About", about_path, class: "nav-link" %>
        <% if Current.user %>
            <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <%=  Current.user.name %>
                </a>
                <ul class="dropdown-menu dropdown-menu-end">
                    <li><%= button_to "Sign Out", signout_path, method: :delete, class: "dropdown-item" %></li>
                </ul>
            </div>
        <% else %>
            <%= link_to "Sign In", signin_path, class: "nav-link" %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_signup_error.html.erb
<% if @user.errors.any? %>
    <div class="col-6 alert alert-danger offset-3 pe-0">
        <% @user.errors.full_messages.each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
<% end %>

app/views/signup/new.html.erb
<div class="container">
<div class="row d-flex justify-content-center mt-4">
<div class="col-8 ">
    <div class="row">
        <h1 class="col mb-4 offset-3">Sign Up</h1>
    </div>
    <%= form_with model: @user, url: signup_path do |form| %>
        <div class="row align-items-center mb-3">
            <%= render "shared/form_error", form: form %>
        </div>
        <div class="row align-items-center mb-3">
            <div class="col-2 offset-3">
                <%= form.label :name %>
            </div>
            <div class="col-4 pe-0">
                <%= form.text_field :name, class: "form-control", placeholder: "John Doe" %>
            </div>
            <div class="col-3 ps-4">
                <span class="form-text"></span>
            </div>
        </div>
        <div class="row align-items-center mb-3">
            <div class="col-2 offset-3">
                <%= form.label :email %>
            </div>
            <div class="col-4 pe-0">
                <%= form.text_field :email, class: "form-control", placeholder: "john@email.com" %>
            </div>
            <div class="col-3 ps-4">
                <span class="form-text"></span>
            </div>
        </div>
        <div class="row align-items-center mb-3">
            <div class="col-2 offset-3">
                <%= form.label :password %>
            </div>
            <div class="col-4 pe-0">
                <%= form.password_field :password, class: "form-control", placeholder: "Password" %>
            </div>
            <div class="col-3 ps-4">
                <span class="form-text">Must more than 6 characters long.</span>
            </div>
        </div>
        <div class="row align-items-center mb-3">
            <div class="col-2 offset-3">
                <%= form.label :password_confirmation %>
            </div>
            <div class="col-4 pe-0">
                <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Comfirm Password" %>
            </div>
            <div class="col-3 ps-4">
                <span class="form-text"></span>
            </div>
        </div>

        <div class="row mt-4 justify-content-end">
            <%= form.submit "Sign Up", class: "col-2 btn btn-primary" %>
            <div class="col-3"></div>
        </div>
    <% end %>
</div>
</div>
</div>

app/views/toys/_form.html.erb
<%= form_with model: toy do |form| %>
    <div class="row align-items-center mb-3">
        <%= render "shared/form_error", form: form %>
    </div>
    <div class="row align-items-center mb-3">
        <div class="col-2 offset-3">
            <%= form.label :toy_name %>
        </div>
        <div class="col-4 pe-0">
            <%= form.text_field :toy_name, class: "form-control", placeholder: "Monopoly" %>
        </div>
        <div class="col-3 ps-4">
            <span class="form-text"></span>
        </div>
    </div>
    <div class="row align-items-center mb-3">
        <div class="col-2 offset-3">
            <%= form.label :category %>
        </div>
        <div class="col-4 pe-0">
            <%= form.text_field :category, class: "form-control", placeholder: "Board games" %>
        </div>
    </div>
    <div class="row align-items-center mb-3">
        <div class="col-2 offset-3">
            <%= form.label :description %>
        </div>
        <div class="col-4 pe-0">
            <%= form.text_area :description, class: "form-control", placeholder: "About your toy..." %>
        </div>
    </div>
    <div class="row align-items-center mb-3">
        <div class="col-2 offset-3">
            <%= form.label :images %>
        </div>
        <div class="col-4 pe-0">
            <%= form.file_field :images, multiple: true, class: "form-control" %>
        </div>
    </div>
    <div class="row mt-4 justify-content-end">
        <%= form.submit "List", class: "col-2 btn btn-primary" %>
        <div class="col-3"></div>
    </div>
<% end %>

app/views/toys/_toy.html.erb
<div class="d-flex flex-row align-items-center w-50 my-4 gx-4">
    <%
=begin%>
 <%= image_tag toy.image, class: "w-25"  %> 
<%
=end%>
    <% if toy.images.length == 1 %>
        <%= image_tag toy.images.first, class: "d-block col-3"%>
    <% elsif toy.images.length > 1 %>
        <div id="carouselExampleControls" class="carousel carousel-dark slide col-3" data-bs-ride="carousel">
            <div class="carousel-inner">
                <% toy.images.each do |image| %>
                    <% if image == toy.images.first %>
                        <div class="carousel-item active">
                            <%= image_tag image, class: "d-block w-100"%>
                        </div>
                    <% else %>
                        <div class="carousel-item">
                            <%= image_tag image, class: "d-block w-100"%>
                        </div>
                    <% end %>           
                <% end %>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    <% end %>
    <div class="d-flex flex-column ps-4">
        <div class="d-flex justify-content-between align-items-center">
            <h3><%= toy.toy_name %></h3>
            <% if current_page?(dashboard_path) %>
                <%= link_to "Edit Toy", edit_toy_path(toy) %>
            <% end %>
        </div>
        <p class="fw-light fst-italic"><%= toy.category %></p>
        <%= toy.description %>
        <p class="fw-light mt-4">Added by: <span class="fw-semibold"><%= toy.user.name %></span></p>
    </div>
</div>

app/views/toys/dashboard.html.erb
<div class="container">
    <div class="row d-flex flex-column align-items-center">
        <div class="d-flex align-items-center justify-content-between w-50 my-4">
            <h1>Your toys</h1>
            <%= link_to "List a Toy", new_toy_path, class: "btn btn-primary" %>
        </div>
        <hr class="w-50">
    </div>
    <div class="row d-flex flex-column align-items-center">
        <%= render @toys %>
    </div>
</div>

app/views/toys/edit.html.erb
<div class="container">
<div class="row d-flex justify-content-center mt-4">
<div class="col-8">
    <div class="col d-flex align-items-center">
        <h1 class="col mb-4 offset-3">Edit toy</h1>
        <%= button_to "Delete", @toy, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "btn btn-outline-danger mb-4" %>
        <div class="col-3"></div>
    </div>
    <%= render "form", toy: @toy %>
</div>
</div>
</div>

app/views/toys/index.html.erb
<div class="container">
    <div class="row d-flex flex-column align-items-center">
        <div class="d-flex align-items-center justify-content-between w-50 my-4">
            <h1>Toys</h1>
            <%= link_to "List a Toy", new_toy_path, class: "btn btn-primary" %>
        </div>
        <hr class="w-50">
    </div>
    <div class="row d-flex flex-column align-items-center">
        <%= render @toys %>
    </div>
</div>

app/views/toys/new.html.erb
<div class="container">
<div class="row d-flex justify-content-center mt-4">
<div class="col-8">
    <div class="row">
        <h1 class="col mb-4 offset-3">New toy</h1>
    </div>
    <%= render "form", toy: @toy %>
</div>
</div>
</div>